// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message/rpc_meta.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpc {

  /// <summary>Holder for reflection information generated from Message/rpc_meta.proto</summary>
  public static partial class RpcMetaReflection {

    #region Descriptor
    /// <summary>File descriptor for Message/rpc_meta.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcMetaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZNZXNzYWdlL3JwY19tZXRhLnByb3RvEgNScGMivwEKB1JwY01ldGESJAoH",
            "cmVxdWVzdBgBIAEoCzITLlJwYy5ScGNSZXF1ZXN0TWV0YRImCghyZXNwb25z",
            "ZRgCIAEoCzIULlJwYy5ScGNSZXNwb25zZU1ldGESFQoNY29tcHJlc3NfdHlw",
            "ZRgDIAEoBRIVCg1lbmNvZGluZ190eXBlGAQgASgFEhIKCnJlcXVlc3RfaWQY",
            "BSABKBASJAoKaGVhcnRfYmVhdBgGIAEoCzIQLlJwYy5ScGNIZWFyQmVhdCKu",
            "AQoOUnBjUmVxdWVzdE1ldGESFAoMc2VydmljZV9uYW1lGAEgASgJEhMKC21l",
            "dGhvZF9uYW1lGAIgASgJEg4KBm9uZXdheRgDIAEoCBIQCgh0cmFjZV9pZBgF",
            "IAEoCRIPCgdzcGFuX2lkGAYgASgJEhYKDnBhcmVudF9zcGFuX2lkGAcgASgJ",
            "EhAKCGFjdG9yX2lkGAkgASgJEhQKDHJlZW50cmFudF9pZBgKIAEoCSI5Cg9S",
            "cGNSZXNwb25zZU1ldGESEgoKZXJyb3JfY29kZRgBIAEoBRISCgplcnJvcl90",
            "ZXh0GAIgASgJIkoKC1JwY0hlYXJCZWF0EhwKFHJlcXVlc3RfbWlsbGlzZWNv",
            "bmRzGAEgASgQEh0KFXJlc3BvbnNlX21pbGxpc2Vjb25kcxgCIAEoECpECg9S",
            "cGNDb21wcmVzc1R5cGUSGAoUUnBjQ29tcHJlc3NUeXBlX05vbmUQABIXChNS",
            "cGNDb21wcmVzc1R5cGVfTFo0EAEqYwoPUnBjRW5jb2RpbmdUeXBlEhgKFFJw",
            "Y0VuY29kaW5nVHlwZV9Ob25lEAASGQoVUnBjRW5jb2RpbmdUeXBlX0NlcmFz",
            "EAESGwoXUnBjRW5jb2RpbmdUeXBlX01zZ1BhY2sQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpc.RpcCompressType), typeof(global::Rpc.RpcEncodingType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpc.RpcMeta), global::Rpc.RpcMeta.Parser, new[]{ "Request", "Response", "CompressType", "EncodingType", "RequestId", "HeartBeat" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpc.RpcRequestMeta), global::Rpc.RpcRequestMeta.Parser, new[]{ "ServiceName", "MethodName", "Oneway", "TraceId", "SpanId", "ParentSpanId", "ActorId", "ReentrantId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpc.RpcResponseMeta), global::Rpc.RpcResponseMeta.Parser, new[]{ "ErrorCode", "ErrorText" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpc.RpcHearBeat), global::Rpc.RpcHearBeat.Parser, new[]{ "RequestMilliseconds", "ResponseMilliseconds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RpcCompressType {
    [pbr::OriginalName("RpcCompressType_None")] None = 0,
    [pbr::OriginalName("RpcCompressType_LZ4")] Lz4 = 1,
  }

  public enum RpcEncodingType {
    [pbr::OriginalName("RpcEncodingType_None")] None = 0,
    [pbr::OriginalName("RpcEncodingType_Ceras")] Ceras = 1,
    [pbr::OriginalName("RpcEncodingType_MsgPack")] MsgPack = 2,
  }

  #endregion

  #region Messages
  public sealed partial class RpcMeta : pb::IMessage<RpcMeta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcMeta> _parser = new pb::MessageParser<RpcMeta>(() => new RpcMeta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcMeta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rpc.RpcMetaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcMeta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcMeta(RpcMeta other) : this() {
      request_ = other.request_ != null ? other.request_.Clone() : null;
      response_ = other.response_ != null ? other.response_.Clone() : null;
      compressType_ = other.compressType_;
      encodingType_ = other.encodingType_;
      requestId_ = other.requestId_;
      heartBeat_ = other.heartBeat_ != null ? other.heartBeat_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcMeta Clone() {
      return new RpcMeta(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::Rpc.RpcRequestMeta request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rpc.RpcRequestMeta Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::Rpc.RpcResponseMeta response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rpc.RpcResponseMeta Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "compress_type" field.</summary>
    public const int CompressTypeFieldNumber = 3;
    private int compressType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CompressType {
      get { return compressType_; }
      set {
        compressType_ = value;
      }
    }

    /// <summary>Field number for the "encoding_type" field.</summary>
    public const int EncodingTypeFieldNumber = 4;
    private int encodingType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EncodingType {
      get { return encodingType_; }
      set {
        encodingType_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 5;
    private long requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "heart_beat" field.</summary>
    public const int HeartBeatFieldNumber = 6;
    private global::Rpc.RpcHearBeat heartBeat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rpc.RpcHearBeat HeartBeat {
      get { return heartBeat_; }
      set {
        heartBeat_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcMeta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcMeta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      if (CompressType != other.CompressType) return false;
      if (EncodingType != other.EncodingType) return false;
      if (RequestId != other.RequestId) return false;
      if (!object.Equals(HeartBeat, other.HeartBeat)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (CompressType != 0) hash ^= CompressType.GetHashCode();
      if (EncodingType != 0) hash ^= EncodingType.GetHashCode();
      if (RequestId != 0L) hash ^= RequestId.GetHashCode();
      if (heartBeat_ != null) hash ^= HeartBeat.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (CompressType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CompressType);
      }
      if (EncodingType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EncodingType);
      }
      if (RequestId != 0L) {
        output.WriteRawTag(41);
        output.WriteSFixed64(RequestId);
      }
      if (heartBeat_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HeartBeat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (CompressType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CompressType);
      }
      if (EncodingType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EncodingType);
      }
      if (RequestId != 0L) {
        output.WriteRawTag(41);
        output.WriteSFixed64(RequestId);
      }
      if (heartBeat_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HeartBeat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (CompressType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CompressType);
      }
      if (EncodingType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EncodingType);
      }
      if (RequestId != 0L) {
        size += 1 + 8;
      }
      if (heartBeat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeartBeat);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcMeta other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::Rpc.RpcRequestMeta();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::Rpc.RpcResponseMeta();
        }
        Response.MergeFrom(other.Response);
      }
      if (other.CompressType != 0) {
        CompressType = other.CompressType;
      }
      if (other.EncodingType != 0) {
        EncodingType = other.EncodingType;
      }
      if (other.RequestId != 0L) {
        RequestId = other.RequestId;
      }
      if (other.heartBeat_ != null) {
        if (heartBeat_ == null) {
          HeartBeat = new global::Rpc.RpcHearBeat();
        }
        HeartBeat.MergeFrom(other.HeartBeat);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (request_ == null) {
              Request = new global::Rpc.RpcRequestMeta();
            }
            input.ReadMessage(Request);
            break;
          }
          case 18: {
            if (response_ == null) {
              Response = new global::Rpc.RpcResponseMeta();
            }
            input.ReadMessage(Response);
            break;
          }
          case 24: {
            CompressType = input.ReadInt32();
            break;
          }
          case 32: {
            EncodingType = input.ReadInt32();
            break;
          }
          case 41: {
            RequestId = input.ReadSFixed64();
            break;
          }
          case 50: {
            if (heartBeat_ == null) {
              HeartBeat = new global::Rpc.RpcHearBeat();
            }
            input.ReadMessage(HeartBeat);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (request_ == null) {
              Request = new global::Rpc.RpcRequestMeta();
            }
            input.ReadMessage(Request);
            break;
          }
          case 18: {
            if (response_ == null) {
              Response = new global::Rpc.RpcResponseMeta();
            }
            input.ReadMessage(Response);
            break;
          }
          case 24: {
            CompressType = input.ReadInt32();
            break;
          }
          case 32: {
            EncodingType = input.ReadInt32();
            break;
          }
          case 41: {
            RequestId = input.ReadSFixed64();
            break;
          }
          case 50: {
            if (heartBeat_ == null) {
              HeartBeat = new global::Rpc.RpcHearBeat();
            }
            input.ReadMessage(HeartBeat);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RpcRequestMeta : pb::IMessage<RpcRequestMeta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcRequestMeta> _parser = new pb::MessageParser<RpcRequestMeta>(() => new RpcRequestMeta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcRequestMeta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rpc.RpcMetaReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcRequestMeta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcRequestMeta(RpcRequestMeta other) : this() {
      serviceName_ = other.serviceName_;
      methodName_ = other.methodName_;
      oneway_ = other.oneway_;
      traceId_ = other.traceId_;
      spanId_ = other.spanId_;
      parentSpanId_ = other.parentSpanId_;
      actorId_ = other.actorId_;
      reentrantId_ = other.reentrantId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcRequestMeta Clone() {
      return new RpcRequestMeta(this);
    }

    /// <summary>Field number for the "service_name" field.</summary>
    public const int ServiceNameFieldNumber = 1;
    private string serviceName_ = "";
    /// <summary>
    ///服务的名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ServiceName {
      get { return serviceName_; }
      set {
        serviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "method_name" field.</summary>
    public const int MethodNameFieldNumber = 2;
    private string methodName_ = "";
    /// <summary>
    ///函数名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MethodName {
      get { return methodName_; }
      set {
        methodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oneway" field.</summary>
    public const int OnewayFieldNumber = 3;
    private bool oneway_;
    /// <summary>
    ///是否不需要返回值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Oneway {
      get { return oneway_; }
      set {
        oneway_ = value;
      }
    }

    /// <summary>Field number for the "trace_id" field.</summary>
    public const int TraceIdFieldNumber = 5;
    private string traceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TraceId {
      get { return traceId_; }
      set {
        traceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "span_id" field.</summary>
    public const int SpanIdFieldNumber = 6;
    private string spanId_ = "";
    /// <summary>
    ///处理过程中小的请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SpanId {
      get { return spanId_; }
      set {
        spanId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parent_span_id" field.</summary>
    public const int ParentSpanIdFieldNumber = 7;
    private string parentSpanId_ = "";
    /// <summary>
    ///当前请求的上层请求
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ParentSpanId {
      get { return parentSpanId_; }
      set {
        parentSpanId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "actor_id" field.</summary>
    public const int ActorIdFieldNumber = 9;
    private string actorId_ = "";
    /// <summary>
    ///ActorRPC的对象唯一ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActorId {
      get { return actorId_; }
      set {
        actorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reentrant_id" field.</summary>
    public const int ReentrantIdFieldNumber = 10;
    private string reentrantId_ = "";
    /// <summary>
    ///可重入ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ReentrantId {
      get { return reentrantId_; }
      set {
        reentrantId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcRequestMeta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcRequestMeta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServiceName != other.ServiceName) return false;
      if (MethodName != other.MethodName) return false;
      if (Oneway != other.Oneway) return false;
      if (TraceId != other.TraceId) return false;
      if (SpanId != other.SpanId) return false;
      if (ParentSpanId != other.ParentSpanId) return false;
      if (ActorId != other.ActorId) return false;
      if (ReentrantId != other.ReentrantId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServiceName.Length != 0) hash ^= ServiceName.GetHashCode();
      if (MethodName.Length != 0) hash ^= MethodName.GetHashCode();
      if (Oneway != false) hash ^= Oneway.GetHashCode();
      if (TraceId.Length != 0) hash ^= TraceId.GetHashCode();
      if (SpanId.Length != 0) hash ^= SpanId.GetHashCode();
      if (ParentSpanId.Length != 0) hash ^= ParentSpanId.GetHashCode();
      if (ActorId.Length != 0) hash ^= ActorId.GetHashCode();
      if (ReentrantId.Length != 0) hash ^= ReentrantId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ServiceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServiceName);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MethodName);
      }
      if (Oneway != false) {
        output.WriteRawTag(24);
        output.WriteBool(Oneway);
      }
      if (TraceId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TraceId);
      }
      if (SpanId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SpanId);
      }
      if (ParentSpanId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ParentSpanId);
      }
      if (ActorId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ActorId);
      }
      if (ReentrantId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ReentrantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ServiceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ServiceName);
      }
      if (MethodName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MethodName);
      }
      if (Oneway != false) {
        output.WriteRawTag(24);
        output.WriteBool(Oneway);
      }
      if (TraceId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TraceId);
      }
      if (SpanId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SpanId);
      }
      if (ParentSpanId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ParentSpanId);
      }
      if (ActorId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ActorId);
      }
      if (ReentrantId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ReentrantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServiceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceName);
      }
      if (MethodName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MethodName);
      }
      if (Oneway != false) {
        size += 1 + 1;
      }
      if (TraceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TraceId);
      }
      if (SpanId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpanId);
      }
      if (ParentSpanId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentSpanId);
      }
      if (ActorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActorId);
      }
      if (ReentrantId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReentrantId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcRequestMeta other) {
      if (other == null) {
        return;
      }
      if (other.ServiceName.Length != 0) {
        ServiceName = other.ServiceName;
      }
      if (other.MethodName.Length != 0) {
        MethodName = other.MethodName;
      }
      if (other.Oneway != false) {
        Oneway = other.Oneway;
      }
      if (other.TraceId.Length != 0) {
        TraceId = other.TraceId;
      }
      if (other.SpanId.Length != 0) {
        SpanId = other.SpanId;
      }
      if (other.ParentSpanId.Length != 0) {
        ParentSpanId = other.ParentSpanId;
      }
      if (other.ActorId.Length != 0) {
        ActorId = other.ActorId;
      }
      if (other.ReentrantId.Length != 0) {
        ReentrantId = other.ReentrantId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ServiceName = input.ReadString();
            break;
          }
          case 18: {
            MethodName = input.ReadString();
            break;
          }
          case 24: {
            Oneway = input.ReadBool();
            break;
          }
          case 42: {
            TraceId = input.ReadString();
            break;
          }
          case 50: {
            SpanId = input.ReadString();
            break;
          }
          case 58: {
            ParentSpanId = input.ReadString();
            break;
          }
          case 74: {
            ActorId = input.ReadString();
            break;
          }
          case 82: {
            ReentrantId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ServiceName = input.ReadString();
            break;
          }
          case 18: {
            MethodName = input.ReadString();
            break;
          }
          case 24: {
            Oneway = input.ReadBool();
            break;
          }
          case 42: {
            TraceId = input.ReadString();
            break;
          }
          case 50: {
            SpanId = input.ReadString();
            break;
          }
          case 58: {
            ParentSpanId = input.ReadString();
            break;
          }
          case 74: {
            ActorId = input.ReadString();
            break;
          }
          case 82: {
            ReentrantId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RpcResponseMeta : pb::IMessage<RpcResponseMeta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcResponseMeta> _parser = new pb::MessageParser<RpcResponseMeta>(() => new RpcResponseMeta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcResponseMeta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rpc.RpcMetaReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcResponseMeta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcResponseMeta(RpcResponseMeta other) : this() {
      errorCode_ = other.errorCode_;
      errorText_ = other.errorText_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcResponseMeta Clone() {
      return new RpcResponseMeta(this);
    }

    /// <summary>Field number for the "error_code" field.</summary>
    public const int ErrorCodeFieldNumber = 1;
    private int errorCode_;
    /// <summary>
    ///错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = value;
      }
    }

    /// <summary>Field number for the "error_text" field.</summary>
    public const int ErrorTextFieldNumber = 2;
    private string errorText_ = "";
    /// <summary>
    ///错误描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ErrorText {
      get { return errorText_; }
      set {
        errorText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcResponseMeta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcResponseMeta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorCode != other.ErrorCode) return false;
      if (ErrorText != other.ErrorText) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorCode != 0) hash ^= ErrorCode.GetHashCode();
      if (ErrorText.Length != 0) hash ^= ErrorText.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (ErrorText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ErrorCode);
      }
      if (ErrorText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorText);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ErrorCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrorCode);
      }
      if (ErrorText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorText);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcResponseMeta other) {
      if (other == null) {
        return;
      }
      if (other.ErrorCode != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.ErrorText.Length != 0) {
        ErrorText = other.ErrorText;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            ErrorText = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorCode = input.ReadInt32();
            break;
          }
          case 18: {
            ErrorText = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RpcHearBeat : pb::IMessage<RpcHearBeat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcHearBeat> _parser = new pb::MessageParser<RpcHearBeat>(() => new RpcHearBeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcHearBeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rpc.RpcMetaReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcHearBeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcHearBeat(RpcHearBeat other) : this() {
      requestMilliseconds_ = other.requestMilliseconds_;
      responseMilliseconds_ = other.responseMilliseconds_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcHearBeat Clone() {
      return new RpcHearBeat(this);
    }

    /// <summary>Field number for the "request_milliseconds" field.</summary>
    public const int RequestMillisecondsFieldNumber = 1;
    private long requestMilliseconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RequestMilliseconds {
      get { return requestMilliseconds_; }
      set {
        requestMilliseconds_ = value;
      }
    }

    /// <summary>Field number for the "response_milliseconds" field.</summary>
    public const int ResponseMillisecondsFieldNumber = 2;
    private long responseMilliseconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ResponseMilliseconds {
      get { return responseMilliseconds_; }
      set {
        responseMilliseconds_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcHearBeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcHearBeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestMilliseconds != other.RequestMilliseconds) return false;
      if (ResponseMilliseconds != other.ResponseMilliseconds) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestMilliseconds != 0L) hash ^= RequestMilliseconds.GetHashCode();
      if (ResponseMilliseconds != 0L) hash ^= ResponseMilliseconds.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestMilliseconds != 0L) {
        output.WriteRawTag(9);
        output.WriteSFixed64(RequestMilliseconds);
      }
      if (ResponseMilliseconds != 0L) {
        output.WriteRawTag(17);
        output.WriteSFixed64(ResponseMilliseconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestMilliseconds != 0L) {
        output.WriteRawTag(9);
        output.WriteSFixed64(RequestMilliseconds);
      }
      if (ResponseMilliseconds != 0L) {
        output.WriteRawTag(17);
        output.WriteSFixed64(ResponseMilliseconds);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestMilliseconds != 0L) {
        size += 1 + 8;
      }
      if (ResponseMilliseconds != 0L) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcHearBeat other) {
      if (other == null) {
        return;
      }
      if (other.RequestMilliseconds != 0L) {
        RequestMilliseconds = other.RequestMilliseconds;
      }
      if (other.ResponseMilliseconds != 0L) {
        ResponseMilliseconds = other.ResponseMilliseconds;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            RequestMilliseconds = input.ReadSFixed64();
            break;
          }
          case 17: {
            ResponseMilliseconds = input.ReadSFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            RequestMilliseconds = input.ReadSFixed64();
            break;
          }
          case 17: {
            ResponseMilliseconds = input.ReadSFixed64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
